table Table
	lineageTag: 4a57747b-c5a9-4f8d-9302-46a7df80b58d

	column Column1
		dataType: string
		lineageTag: 46bdd799-4d7b-41b4-b631-16d7dcb096ec
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: int64
		formatString: 0
		lineageTag: 564dd98f-f123-4211-9e3f-8f7402b22edf
		summarizeBy: sum
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	partition Table = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WcnRU0lEyNDAwUIqNBQA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t, Column2 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

